version: "2"
services:
  writer:
    image: "registry.infomaker.io/writer:latest"
    env_file:
      - ./writer-dev.env
    ports:
      - "16777:80"
      - "5000:5000"
    depends_on:
      - editorservice
      - conceptsbackend
  conceptsbackend:
    image: "registry.infomaker.io/conceptsbackend:latest"
    env_file:
      - ./conceptsbackend-dev.env
    ports:
      - "3000:3000"
  editorservice:
    image: "registry.infomaker.io/editorservice:latest"
    env_file:
      - ./editorservice-dev.env
    ports:
      - "8181:8181"